version: '3.8'

services:
  app:
    command: npm run dev
    build:
      context: .
      target: development
    ports:
      - 5000:5000
    volumes:
      - ./:/app
      - /app/node_modules

volumes:
  meili:
  redis:
